### ISSUE TITLE
Reshaper and Nunit can't instantiate gameObject

### ISSUE THREAD

**Issue by Baccanno** [networm/NCrunchAdapterForUnity#2]
[This issue is fixed see next posts]
As you posted this repo as a work around in issue : https://issuetracker.unity3d.com/issues/targetinvocationexception-when-running-nunit-tests-in-visual-studio

I tried to install it. However we still have the same stacktrace rising up. And tests failing as inconclusive.

How do we check installation ?

```2018.04.06 10:39:39.771   ERROR System.Reflection.TargetInvocationException: Une exception a été levée par la cible d'un appel.
System.Reflection.TargetInvocationException: Une exception a été levée par la cible d'un appel. ---> System.InvalidCastException: Impossible d'effectuer un cast du proxy transparent en type 'System.Web.UI.ICallbackEventHandler'.
   à NUnit.Framework.Api.FrameworkController.LoadTestsAction..ctor(FrameworkController controller, Object handler)
   --- Fin de la trace de la pile d'exception interne ---

Server stack trace: 
   à System.RuntimeMethodHandle.InvokeMethod(Object target, Object[] arguments, Signature sig, Boolean constructor)
   à System.Reflection.RuntimeConstructorInfo.Invoke(BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
   à System.RuntimeType.CreateInstanceImpl(BindingFlags bindingAttr, Binder binder, Object[] args, CultureInfo culture, Object[] activationAttributes, StackCrawlMark& stackMark)
   à System.Activator.CreateInstance(Type type, BindingFlags bindingAttr, Binder binder, Object[] args, CultureInfo culture, Object[] activationAttributes)
   à System.Activator.CreateInstance(String assemblyString, String typeName, Boolean ignoreCase, BindingFlags bindingAttr, Binder binder, Object[] args, CultureInfo culture, Object[] activationAttributes, Evidence securityInfo, StackCrawlMark& stackMark)
   à System.Activator.CreateInstance(String assemblyName, String typeName, Boolean ignoreCase, BindingFlags bindingAttr, Binder binder, Object[] args, CultureInfo culture, Object[] activationAttributes, Evidence securityInfo)
   à System.AppDomain.CreateInstance(String assemblyName, String typeName, Boolean ignoreCase, BindingFlags bindingAttr, Binder binder, Object[] args, CultureInfo culture, Object[] activationAttributes, Evidence securityAttributes)
   à System.AppDomain.CreateInstanceAndUnwrap(String assemblyName, String typeName, Boolean ignoreCase, BindingFlags bindingAttr, Binder binder, Object[] args, CultureInfo culture, Object[] activationAttributes, Evidence securityAttributes)
   à System.Runtime.Remoting.Messaging.StackBuilderSink._PrivateProcessMessage(IntPtr md, Object[] args, Object server, Object[]& outArgs)
   à System.Runtime.Remoting.Messaging.StackBuilderSink.SyncProcessMessage(IMessage msg)

Exception rethrown at [0]: 
   à System.Runtime.Remoting.Proxies.RealProxy.HandleReturnMessage(IMessage reqMsg, IMessage retMsg)
   à System.Runtime.Remoting.Proxies.RealProxy.PrivateInvoke(MessageData& msgData, Int32 type)
   à System.AppDomain.CreateInstanceAndUnwrap(String assemblyName, String typeName, Boolean ignoreCase, BindingFlags bindingAttr, Binder binder, Object[] args, CultureInfo culture, Object[] activationAttributes, Evidence securityAttributes)
   à NUnit.Engine.Drivers.NUnit3FrameworkDriver.Load(String testAssemblyPath, IDictionary`2 settings)
   à NUnit.Engine.Runners.DirectTestRunner.LoadPackage()
   à NUnit.Engine.Runners.DirectTestRunner.EnsurePackageIsLoaded()
   à NUnit.Engine.Runners.DirectTestRunner.Explore(TestFilter filter)
   à NUnit.Engine.Runners.MasterTestRunner.Explore(TestFilter filter)
   à JetBrains.ReSharper.UnitTestRunner.nUnit30.BuiltInNUnitRunner.<>c__DisplayClass1.<RunTests>b__0() dans c:\Build Agent\work\7d5280ba349465b8\Psi.Features\UnitTesting\nUnit\Runner30\Src\BuiltInNUnitRunner.cs:ligne 65
   à JetBrains.ReSharper.UnitTestRunner.nUnit30.BuiltInNUnitRunner.WithExtensiveErrorHandling(IRemoteTaskServer server, Action action) dans c:\Build Agent\work\7d5280ba349465b8\Psi.Features\UnitTesting\nUnit\Runner30\Src\BuiltInNUnitRunner.cs:ligne 827

```

**Comment by Baccanno** [comment]
[Also fixed see next post]
After restarting unity, nunit references are broken in all the projects generated by unity (using asmdef), including the regular Plugins project.

**Comment by Baccanno** [comment]
Allright, path in NCrunchAdapterForUnity was hard coded. had to change it to reflect our project structure. Though now there is an issue with Lazy<T> conflicting (we are using unity .net 4)

Using Nunit .net 4 version might fix this ?

Severity	Code	Description	Project	File	Line	Suppression State
Error	CS0433	The type 'Lazy<T>' exists in both 'nunit.framework, Version=3.5.0.0, Culture=neutral, PublicKeyToken=2638cd05610744eb' and 'mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089'

**Comment by networm** [comment]
Since you have said that using asmdef in your project, the unity version you use is 2017.3+. I have checked nunit version packaged in unity is still 3.5.0 both in 2017.3.0f3 and 2017.4.0f3.
The first thing you should know is that unity compile project using its packaged nunit and you use another nunit in Visual Studio. So if you encounter this error in unity, just disable your nunit dll in import settings (unselect Editor platform). If you encounter this error in Visual Studio, modify NCrunchAdapterForUnity code to change packaged nunit reference to your customed nunit reference.

**Comment by networm** [comment]
The principle is that you should only have one nunit reference for each environment sucn as unity or visual studio.

**Comment by Baccanno** [comment]
Thanks for your answers 

I don't get your "If you encounter this error in Visual Studio, modify NCrunchAdapterForUnity code to change packaged nunit reference to your customed nunit reference." 

This is I believe what I've tried I replaced the path in NCrunchAdapterForUnity with my own dll path. 
At that time the Lazy conflict appearead. I thought it could be related to the .net version Nunit was compiled to (you deliver with 3.5 and I use the 4.0 feature) but the problem persists.

**Comment by networm** [comment]
You should remove NCrunchAdapterForUnity nunit.dll first and then use your own dll.

**Comment by networm** [comment]
Where the Lazy conflict appears? Unity console output or Resharper unit test window?

**Comment by Baccanno** [comment]
> You should remove NCrunchAdapterForUnity nunit.dll first and then use your own dll.

This is what I did, removed net35 folder and put net40 

> Where the Lazy conflict appears? Unity console output or Resharper unit test window?

It was a compilation issue in Unity editor console.

**Comment by networm** [comment]
As I suggested before, you should uncheck Editor platform in your custom 4.0 nunit dll import settings.

**Comment by Baccanno** [comment]
Everything compiles now. I must have forgotten something in the way. Though Can't get to create a game object in tests.
This simple test fails in constructor with a SecurityException. I guess it is as predicted as unity team. They have their own magic working there ..
       [Test]
        public void NewGameObject()
        {
            var go = new GameObject();
        }

**Comment by networm** [comment]
Yes you couldn't call any unity api in unit test. Unity's built in test runner is just integration test. You could search about related issues on unity forum.
You could just write pure C# code in unit test.

**Comment by Baccanno** [comment]
Allright, 
It seems that Rider is gonna have something on that. And that is great to hear. 
https://github.com/JetBrains/resharper-unity/issues/96
